{% set name = "des-desmeds" %}
{% set version = "0.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/desmeds/archive/v{{ version }}.tar.gz
  sha256: 367604c3ff255e559ff9f6195cd0c3a154098995b77fa83ac445ebbdba4605d4

build:
  # the setup.py uses the `scripts` argument to distutils so this recipe
  # cannot be noarch: python
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fitsio
    - des-easyaccess
    - meds
    - esutil
    - pyyaml
    - numpy
    - psfex
    - piff
    - pixmappy
    - cfitsio

test:
  imports:
    - desmeds

about:
  home: https://github.com/esheldon/desmeds
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: DES-specific MEDS production code
  doc_url: https://github.com/esheldon/desmeds
  dev_url: https://github.com/esheldon/desmeds

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
